---
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      ref:
        description: The Git ref to deploy
        required: false
        default: ''

env:
  DISTRIBUTION_ID: E2461OP4YFCUOQ
  BUCKET: inko-lang.org
  AWS_DEFAULT_REGION: eu-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'inko-lang/website' && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: build
          key: ${{ runner.os }}-deploy
      - run: rake deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
